### ISSUE TITLE
push encoders issue

### ISSUE THREAD

**Issue by tizfra** [Shuptuu/TheLink#3]
Hi, 
first of all congratulations for the software, I think you made perfect software, but i've found that the order of push encoders isn't like the software tab.
If I push the second encoder xair edit opens the third tab,
If I push the third encoder xair edit opens the second tab,
If I push the fifth encoder xair edit opens the sixth tab,
If I push the sixth encoder xair edit opens the fifth tab.

**Comment by Shuptuu** [comment]
Hi,
Thanks. It's because the encoder buttons are not made to navigate across tabs in Air Edit. They allow to select encoder mode: Fader/Gain/Pan/Gate/Comp/EQ/DCA/Tap
And according the selected mode, it opens the most relevant tab in Air Edit.
Small change in version 1.6: It keeps the Mixer tab for Fader, Gain and Pan mode.
I suggest you to have a look to the user manual or to the overlay to understand buttons functions
